### ISSUE TITLE
Versão do PHP

### ISSUE THREAD

**Issue by alansystem** [vmnog/phpeiros-loja#10]
Pergunta, esse sistema não roda bem na versão do PHP mais baixa? Como por exemplo a 5.6?

Porque aqui bugou várias coisas, sei que gostariam de manter na versão mais nova, porém recomendo uma descrição de requisitos mínimos no README.

**Comment by maicomferre** [comment]
Sim. Alguns elementos utilizados no código são do php 7/7.1. 
Por favor, atualize seu PHP para a versão mais recentes.
