### ISSUE TITLE
Campo para imagem do produto

### ISSUE THREAD

**Issue by vmnog** [vmnog/phpeiros-loja#2]
Seria interessante implementar um campo no formulário do produto onde pudessemos fazer upload da imagem do produto e isso ser mostrado quando clicamos para visualizar o produto, acredito que tenha uma linha comentada lá, mas a funcionalidade não existe ainda no formulário e nem no banco.

**Comment by rodrigosousadf** [comment]
tinha lido em algum lugar que era melhor salvar a imagem em algum lugar e salvar o link da imagem no banco de dados.

**Comment by maicomferre** [comment]
![image](https://user-images.githubusercontent.com/40906484/58300441-d6a36e00-7db8-11e9-8ad9-e713ab45d931.png)
![image](https://user-images.githubusercontent.com/40906484/58300462-f5a20000-7db8-11e9-8a6f-8b9811b27841.png)
![image](https://user-images.githubusercontent.com/40906484/58300469-fdfa3b00-7db8-11e9-8039-5c9724eaa68a.png)

Eu fiz assim, ele salva apenas o nome que ele gera com md5(nome aleatório) e dai ele salva este nome no banco de dados e armazena a imagem em uma pasta especifica, quando vai requisitar esta imagem apenas consulta no banco de dados já ciente da pasta onde ela se localiza.

**Comment by vmnog** [comment]
Ficou muito bom maicom! Acha que podemos encerrar o issue?

**Comment by maicomferre** [comment]
> Ficou muito bom maicom! Acha que podemos encerrar o issue?

Sim. O programa deve futuramente poder receber múltiplas imagens, mas até agora ele resolve o problema da ausência das imagens.

Ah, ele também resolve o problema da  #1 
![image](https://user-images.githubusercontent.com/40906484/58332193-0da56e00-7e11-11e9-9571-82c7439271e3.png)

**Comment by vmnog** [comment]
Perfeito! fecharei  esta issue  e a #1
