### ISSUE TITLE
Não encontrei o SQL

### ISSUE THREAD

**Issue by alansystem** [vmnog/phpeiros-loja#3]
Não encontrei SQL para criação do banco de dados.

Onde encontro?

**Comment by rodrigosousadf** [comment]
Tá usando xamp?

Em qui, 23 de mai de 2019 10:26, Alan Nogueira <notifications@github.com>
escreveu:

**Comment by rodrigosousadf** [comment]
tem que instalar o sql e gerar um banco. podemos fazer um arquivo .sql e deixar na pasta, ai vai com os dados do que tu precisa gerar, mas se instalar o xamp, na hora que tu adicionar produto acredito que ele já crie o banco de dados.

**Comment by alansystem** [comment]
Boa, criei um banco e ele criou a tabela categorias e produtos.

Porém quando fui adicionar categoria me retornou o seguinte:

A categoria teste não foi adicionada: Table 'loja.categorias' doesn't exist

Isso é algo que deve ser corrigido?

**Comment by alansystem** [comment]
Ah entendi agora, obrigatoriamente o banco de dados tem que ter o nome "loja" , eu troquei no conecta.php para outro nome, mas agora recriei com o nome loja e funcionou, mas isso não é relativamente ruim? Forçar o cara manter o nome "loja" ? Eu mesmo tinha já um banco com esse nome e tive que substituir.

**Comment by vmnog** [comment]
Acho que é bom manter o mesmo nome do banco, pq assim a gente consegue apenas clonar o arquivo e usar a nova versão do projeto, mas pode ser algo mais incomum do que só loja.

talvez loja-phpeiros seria um nome adequado.

a ideia era que ao clonar o repositório o banco e tabelas fossem criados sozinhos (caso não existam).

Estranho não ter funcionado com você.. acho que foi por que vc ja tinha um banco com nome loja?!

**Comment by alansystem** [comment]
Sim perfeito, comigo não tinha funcionado porque o nome estava diferente, mas resolvido.

Vamos manter nome "loja" mesmo, agora entendi a ideia. Boa!
