### ISSUE TITLE
Usar o materialize ao invés do bootstrap

### ISSUE THREAD

**Issue by rodrigosousadf** [vmnog/phpeiros-loja#4]
o materialize tá em alta, é um library mais bonitinha que o bootstrap. poderíamos usar ele.

**Comment by vmnog** [comment]
A ideia não é ruim, mas será que vale a pena? Acredito que a comunidade do bootstrap seja maior e por sua vez teriamos mais lugares pra consultar quando enfrentarmos problemas..

**Comment by alansystem** [comment]
Materialize CSS é bacana, já fiz um projeto todo com ela, mas realmente Bootstrap é mais popular, isso a longo prazo na minha opinião faz diferença! Mas é somente uma opinião.

**Comment by vmnog** [comment]
Acha que devemos continuar com bootstrap então já que a comunidade é maior?

**Comment by alansystem** [comment]
Meu voto é sim! Apesar de eu conhecer ambos e ter trabalhado com ambos.

**Comment by vmnog** [comment]
Ok, continuaremos com bootstrap então.
