### ISSUE TITLE
interessante aprender a usar o datatables

### ISSUE THREAD

**Issue by rodrigosousadf** [vmnog/phpeiros-loja#5]
https://datatables.net/ se puderam dar um olhada, ajuda muito a mexer com tabelas.

**Comment by vmnog** [comment]
Parece interessante, vai facilitar bastante o trabalho, parece que usa bastante javascript né? 
Eu tinha pensado em tentar fazer com php mas pode ser que não valha o esforço

Alguém quer tentar implementar isso?

**Comment by alansystem** [comment]
Se esse projeto fosse em codeigniter teria o https://grocerycrud.com que monta tudo sozinho.

**Comment by vmnog** [comment]
Queremos focar no aprendizado mais voltado ao php, então acredito que podemos tentar implementar esse grocery crud no projeto.

Não conheço muito deste codeigniter, caso decidissemos usar ele, teriamos que refazer o código que temos? ou podemos simplesmente acrescentar uma parte dele no projeto juntamente com o php puro?

**Comment by alansystem** [comment]
Então, Grocery Crud é uma extensão do Framewrok Codeigniter.

Codeigniter eu arriscaria dizer que é o Framework PHP mais simples e mais objetivo, ele mantém a organização na estrutura MVC (Model, View, Controller), além da facilidade de lidar com o banco e etc... 

Porém terá sim que trocar toda a estrutura do projeto, isso eu poderia fazer, daria um trabalhinho mas a longo prazo ficaria excelente, inclusive seria a primeira loja virtual open source em codeigniter, já procurei e não achei nenhuma que funcionasse.

**Comment by vmnog** [comment]
Será que usar um framework não "tiraria a graça" do aprendizado? Pq não estamos tentando fazer algo com prazo ou pra alguem, o foco é aprender, talvez se fizessemos as funções do grocery crud manualmente valeria mais a pena. Talvez não valeria a pena em questoes de tempo que levaríamos pra fazer mas com certeza vale a pena pelo aprendizado que teríamos fazendo isso.

**Comment by alansystem** [comment]
Você tem razão, framework é bom, porém limita na ajuda das pessoas.

Descarta!

**Comment by vmnog** [comment]
Ok! estarei encerrando essa issue!
