### ISSUE TITLE
Reorganizar arquivos

### ISSUE THREAD

**Issue by vmnog** [vmnog/phpeiros-loja#6]
Acho que seria interessante começarmos a manter uma organização em pastas dos arquivos, seria necessário criar diretorios dentro do projeto e tambem alterar o código onde os arquivos sao citados.. o que acham?

ficaria algo mais ou menos assim:
```

-includes+
___________conecta.php
___________cabecalho.php
___________footer.php
-bancos+
___________banco-produto.php
___________banco-categoria.php
etc....
```

**Comment by alansystem** [comment]
Então, estrutura MVC serve exatamente pra isso, você manja?

**Comment by vmnog** [comment]
Já ouvi falar, posso dar uma estudada e tentar implementar.

**Comment by maicomferre** [comment]
Sim. Seria bom organizar, ainda mais dividindo páginas de cliente e administração que está meio misturado no momento.

**Comment by rodrigosousadf** [comment]
dá pra fazer um mini framework, só pra usar os controles e views.
