### ISSUE TITLE
implementar PDO

### ISSUE THREAD

**Issue by rodrigosousadf** [vmnog/phpeiros-loja#7]
pra conexão com o banco de dados seria bom usarmos o PDO, é bem mais seguro.
Já chegaram a ver isso lá no alura?

**Comment by vmnog** [comment]
Ainda não cheguei a ver, seria muito complicado implementar isso no projeto?

**Comment by rodrigosousadf** [comment]
bem tranquilo, muda pouca coisa na hora de conectar
